Repository planetarium/Flawless, pull requests merged in 2022-07, with the labels that each got.

#3 Setup test runner
  Assets/InitTestScene637927218503640400.unity
  Assets/InitTestScene637927218503640400.unity.meta
  Assets/_Scripts/Flawless.asmdef
  Assets/_Scripts/Flawless.asmdef.meta
  Assets/_Scripts/Model.meta
  Assets/_Scripts/Model/Test.cs
  Assets/_Scripts/Model/Test.cs.meta
  Assets/_Scripts/Models.meta
  Assets/_Scripts/Tests.meta
  Assets/_Scripts/Tests/ModelTest.cs
  Assets/_Scripts/Tests/ModelTest.cs.meta
  Assets/_Scripts/Tests/Tests.asmdef
  Assets/_Scripts/Tests/Tests.asmdef.meta
Labels: Extra Large

#1 Add models about stages
  Assets/InitTestScene637927226944852998.unity
  Assets/InitTestScene637927226944852998.unity.meta
  Assets/InitTestScene637927232869825753.unity
  Assets/InitTestScene637927232869825753.unity.meta
  Assets/InitTestScene637927235590472677.unity
  Assets/InitTestScene637927235590472677.unity.meta
  Assets/_Scripts/Model/Test.cs
  Assets/_Scripts/Models/BattleEvent.cs
  Assets/_Scripts/Models/BattleEvent.cs.meta
  Assets/_Scripts/Models/IEvent.cs
  Assets/_Scripts/Models/IEvent.cs.meta
  Assets/_Scripts/Models/Section.cs
  Assets/_Scripts/Models/Section.cs.meta
  Assets/_Scripts/Models/ShopEvent.cs
  Assets/_Scripts/Models/ShopEvent.cs.meta
  Assets/_Scripts/Models/Stage.cs
  Assets/_Scripts/Models/Stage.cs.meta
  Assets/_Scripts/Models/WorkshopEvent.cs
  Assets/_Scripts/Models/WorkshopEvent.cs.meta
  Assets/_Scripts/Tests/ModelTest.cs
Labels: Extra Large

#5 Replace Stage.Generate() with Stage.NextEvent()
  Assets/_Scripts/Model.meta
  Assets/_Scripts/Models/Session.cs
  Assets/_Scripts/Models/Stage.cs
  Assets/_Scripts/Tests/ModelTest.cs
Labels: Small

#9 Implement tables
  Assets/_Scripts/Battle/BattleSimulator.cs
  Assets/_Scripts/Battle/Model/Character.cs
  Assets/_Scripts/Battle/Model/ICharacter.cs
  Assets/_Scripts/Battle/Model/Skill/AttackSkill.cs
  Assets/_Scripts/Battle/Model/Skill/DownwardSlash.cs
  Assets/_Scripts/Battle/Model/Skill/SkillBase.cs
  Assets/_Scripts/Battle/Model/Skill/SkillFactory.cs
  Assets/_Scripts/Battle/Model/Skill/SkillFactory.cs.meta
  Assets/_Scripts/Battle/Model/Skill/UpwardSlash.cs
  Assets/_Scripts/Table/Sheet.cs
  Assets/_Scripts/Table/Sheet.cs.meta
  Assets/_Scripts/Table/SkillSheet.cs
  Assets/_Scripts/Table/SkillSheet.cs.meta
  Assets/_Scripts/TableSheets.cs
  Assets/_Scripts/TableSheets.cs.meta
  Assets/_Scripts/Tests/BattleTest.cs
Labels: Large

#12 Add `WeaponSheet`.
  Assets/Resources/TableSheets/WeaponSheet.csv
  Assets/Resources/TableSheets/WeaponSheet.csv.meta
  Assets/_Scripts/Battle/Model/CharacterStat.cs
  Assets/_Scripts/Table/WeaponSheet.cs
  Assets/_Scripts/Table/WeaponSheet.cs.meta
  Assets/_Scripts/Tests/BattleTest.cs
Labels: Small

#13 Revise `PlayerState` and `WeaponState`
  Assets/_Scripts/Actions/SellWeaponAction.cs
  Assets/_Scripts/States/PlayerState.cs
  Assets/_Scripts/States/WeaponState.cs
  Assets/_Scripts/Tests/ActionTest.cs
  Assets/_Scripts/Tests/TestRandom.cs
  Assets/_Scripts/Tests/TestRandom.cs.meta
Labels: Large

#11 Initial `SceneState` implementation
  Assets/_Scripts/Models/Stage.cs
  Assets/_Scripts/States/SceneState.cs
  Assets/_Scripts/States/SceneState.cs.meta
  Assets/_Scripts/Tests/SceneStateTest.cs
  Assets/_Scripts/Tests/SceneStateTest.cs.meta
Labels: Medium

#14 Adjust WeaponState layout
  Assets/_Scripts/Actions/SellWeaponAction.cs
  Assets/_Scripts/States/WeaponState.cs
  Assets/_Scripts/Tests/ActionTest.cs
Labels: Extra Small

#15 `SceneState` added to `PlayerState`
  Assets/_Scripts/States/PlayerState.cs
  Assets/_Scripts/Tests/ActionTest.cs
Labels: Extra Small

#16 Introduce WeaponStateFactory
  Assets/_Scripts/States/WeaponStateFactory.cs
  Assets/_Scripts/States/WeaponStateFactory.cs.meta
  Assets/_Scripts/Table/WeaponSheet.cs
  Assets/_Scripts/Tests/StatesTest.cs
  Assets/_Scripts/Tests/StatesTest.cs.meta
Labels: Medium

#17 Initial `Encounter` implementation
  Assets/_Scripts/Models/Encounters.meta
  Assets/_Scripts/Models/Encounters/BarEncounter.cs
  Assets/_Scripts/Models/Encounters/BarEncounter.cs.meta
  Assets/_Scripts/Models/Encounters/BattleEncounter.cs
  Assets/_Scripts/Models/Encounters/BattleEncounter.cs.meta
  Assets/_Scripts/Models/Encounters/Encounter.cs
  Assets/_Scripts/Models/Encounters/Encounter.cs.meta
  Assets/_Scripts/Models/Encounters/IEncounter.cs
  Assets/_Scripts/Models/Encounters/IEncounter.cs.meta
  Assets/_Scripts/Models/Encounters/SmithEncounter.cs
  Assets/_Scripts/Models/Encounters/SmithEncounter.cs.meta
  Assets/_Scripts/States/SceneState.cs
Labels: Medium

#18 Random utility function
  Assets/_Scripts/Models/Encounters/BarEncounter.cs
  Assets/_Scripts/Models/Encounters/BattleEncounter.cs
  Assets/_Scripts/Models/Encounters/Encounter.cs
  Assets/_Scripts/Models/Encounters/SmithEncounter.cs
  Assets/_Scripts/States/SceneState.cs
  Assets/_Scripts/Utils.cs
  Assets/_Scripts/Utils.cs.meta
Labels: Extra Small

#21 Various actions
  Assets/_Scripts/Actions/CreateAccountAction.cs
  Assets/_Scripts/Actions/CreateAccountAction.cs.meta
  Assets/_Scripts/Actions/CreateAccountActionPlainValue.cs
  Assets/_Scripts/Actions/CreateAccountActionPlainValue.cs.meta
  Assets/_Scripts/Actions/EnterEncounterAction.cs
  Assets/_Scripts/Actions/EnterEncounterAction.cs.meta
  Assets/_Scripts/Actions/EnterStageAction.cs
  Assets/_Scripts/Actions/EnterStageAction.cs.meta
  Assets/_Scripts/Actions/ExitPubAction.cs
  Assets/_Scripts/Actions/ExitPubAction.cs.meta
  Assets/_Scripts/Actions/ExitSmithAction.cs
  Assets/_Scripts/Actions/ExitSmithAction.cs.meta
  Assets/_Scripts/Actions/ResetSessionAction.cs
  Assets/_Scripts/Actions/ResetSessionAction.cs.meta
  Assets/_Scripts/Models/Encounters/Encounter.cs
  Assets/_Scripts/Models/Encounters/PubEncounter.cs
  Assets/_Scripts/Models/Encounters/PubEncounter.cs.meta
  Assets/_Scripts/States/PlayerState.cs
Labels: Large

#22 Flags added
  Assets/_Scripts/States/PlayerState.cs
  Assets/_Scripts/States/SceneState.cs
  Assets/_Scripts/States/StatsState.cs
Labels: Medium

#23 Flag tests added
  Assets/_Scripts/Tests/PlayerStateTest.cs
  Assets/_Scripts/Tests/PlayerStateTest.cs.meta
Labels: Extra Small

#24 Feature/experience
  Assets/_Scripts/States/PlayerState.cs
  Assets/_Scripts/States/StatsState.cs
  Assets/_Scripts/Tests/PlayerStateTest.cs
Labels: Medium

#25 Introduce UpgradeWeaponAction
  Assets/_Scripts/Actions/UpgradeWeaponAction.cs
  Assets/_Scripts/Actions/UpgradeWeaponAction.cs.meta
  Assets/_Scripts/States/PlayerState.cs
  Assets/_Scripts/States/SceneState.cs
  Assets/_Scripts/States/WeaponState.cs
  Assets/_Scripts/Tests/ActionTest.cs
Labels: Extra Large

#28 Dummy enemy implementation
  Assets/_Scripts/Battle/Model/Character.cs
  Assets/_Scripts/Models/Encounters/BattleEncounter.cs
Labels: Extra Small

#31 minor bug fix
  Assets/Scenes/TestScene.unity
  Assets/_Scripts/MonoSingleton.cs
  Assets/_Scripts/Util/LocalizationManager.cs
  Assets/_Scripts/Util/LogExtension.cs
Labels: Extra Small

#32 Extract character from `PlayerState`
  Assets/_Scripts/Battle/Model/Character.cs
  Assets/_Scripts/States/PlayerState.cs
Labels: Extra Small

#35 `PubResetPointsAction` added
  Assets/_Scripts/Actions/PubResetPointsAction.cs
  Assets/_Scripts/Actions/PubResetPointsAction.cs.meta
  Assets/_Scripts/Models/Encounters/PubEncounter.cs
  Assets/_Scripts/States/PlayerState.cs
  Assets/_Scripts/States/SceneState.cs
  Assets/_Scripts/Tests/PlayerStateTest.cs
Labels: Small

#37 Introduce InitalizeStatesAction and EnvironmentState
  Assets/_Scripts/Actions/InitializeStatesAction.cs
  Assets/_Scripts/Actions/InitializeStatesAction.cs.meta
  Assets/_Scripts/Actions/InitializeStatesActionPlainValue.cs
  Assets/_Scripts/Actions/InitializeStatesActionPlainValue.cs.meta
  Assets/_Scripts/States/EnvironmentState.cs
  Assets/_Scripts/States/EnvironmentState.cs.meta
Labels: Medium

#38 Adjust health in actions
  Assets/_Scripts/Actions/EnterEncounterAction.cs
  Assets/_Scripts/Actions/PubHealAction.cs
  Assets/_Scripts/Actions/PubHealAction.cs.meta
  Assets/_Scripts/Actions/ResetSessionAction.cs
  Assets/_Scripts/Actions/SellWeaponAction.cs
  Assets/_Scripts/Models/Encounters/PubEncounter.cs
  Assets/_Scripts/States/PlayerState.cs
Labels: Small

#41 Move Libplanet.Unity
  Assets/Libplanet.Unity.meta
  Assets/Libplanet.Unity/Editor.meta
  Assets/Libplanet.Unity/Editor/AgentMenu.cs
  Assets/Libplanet.Unity/Editor/AgentMenu.cs.meta
  Assets/Libplanet.Unity/Editor/BlockChainMenu.cs
  Assets/Libplanet.Unity/Editor/BlockChainMenu.cs.meta
  Assets/Libplanet.Unity/Editor/GenesisBlockMenu.cs
  Assets/Libplanet.Unity/Editor/GenesisBlockMenu.cs.meta
  Assets/Libplanet.Unity/Editor/PrivateKeyMenu.cs
  Assets/Libplanet.Unity/Editor/PrivateKeyMenu.cs.meta
  Assets/Libplanet.Unity/Editor/SwarmConfigMenu.cs
  Assets/Libplanet.Unity/Editor/SwarmConfigMenu.cs.meta
  Assets/Libplanet.Unity/Editor/UtilsMenu.cs
  Assets/Libplanet.Unity/Editor/UtilsMenu.cs.meta
Labels: Extra Small

#40 Adjust `Encounter` related codes
  Assets/_Scripts/Actions/ExitPubAction.cs
  Assets/_Scripts/Actions/ExitSmithAction.cs
  Assets/_Scripts/Actions/PubResetPointsAction.cs
  Assets/_Scripts/Actions/UpgradeWeaponAction.cs
  Assets/_Scripts/Models/Encounters/Encounter.cs
  Assets/_Scripts/Models/Encounters/SmithEncounter.cs
  Assets/_Scripts/States/SceneState.cs
  Assets/_Scripts/States/WeaponState.cs
  Assets/_Scripts/Tests/ActionTest.cs
  Assets/_Scripts/Utils.cs
Labels: Medium

#46 Create account with full health; weapon state test fix
  Assets/_Scripts/Actions/CreateAccountAction.cs
  Assets/_Scripts/Tests/ActionTest.cs
  Assets/_Scripts/Tests/StatesTest.cs
  Assets/_Scripts/Tests/TestRandom.cs
Labels: Extra Small

#36 implement skill selection ui
  Assets/Prefabs/SkillDesc.prefab
  Assets/Prefabs/SkillDesc.prefab.meta
  Assets/Prefabs/TurnView.prefab
  Assets/Prefabs/TurnView.prefab.meta
  Assets/Resources/Localization/skill_description.csv
  Assets/Resources/Localization/skill_description.csv.meta
  Assets/Resources/Localization/skill_name.csv
  Assets/Resources/TableSheets/SkillSheet.csv
  Assets/Scenes/TestScene.unity
  Assets/_Scripts/Battle/BattleSimulator.cs
  Assets/_Scripts/Battle/Model/Character.cs
  Assets/_Scripts/Battle/Model/CharacterStat.cs
  Assets/_Scripts/Battle/Model/Skill/AnkleCut.cs
  Assets/_Scripts/Battle/Model/Skill/AnkleCut.cs.meta
  Assets/_Scripts/Battle/Model/Skill/HorizontalSlash.cs
  Assets/_Scripts/Battle/Model/Skill/HorizontalSlash.cs.meta
  Assets/_Scripts/Battle/Model/Skill/SkillFactory.cs
  Assets/_Scripts/Battle/Model/Weapon.cs
  Assets/_Scripts/Battle/SkillLog.cs
  Assets/_Scripts/EncounterHandler.cs
  Assets/_Scripts/EncounterHandler.cs.meta
  Assets/_Scripts/Table/TableManager.cs
  Assets/_Scripts/Table/TableManager.cs.meta
  Assets/_Scripts/UI/BattleSkillDecision.cs
  Assets/_Scripts/UI/BattleSkillDecision.cs.meta
  Assets/_Scripts/UI/BattleUI.cs
  Assets/_Scripts/UI/SkillSelectPopup.cs
  Assets/_Scripts/UI/SkillSelectPopup.cs.meta
  Assets/_Scripts/UI/StatView.cs
  Assets/_Scripts/UI/TextButton.cs
  Assets/_Scripts/UI/TextButton.cs.meta
  Assets/_Scripts/UI/TurnView.cs
  Assets/_Scripts/UI/TurnView.cs.meta
  Assets/_Scripts/Util/LocalizationManager.cs
  Assets/_Scripts/Util/LogExtension.cs
Labels: Extra Large

#50 Remove free conditions
  Assets/_Scripts/Actions/PubHealAction.cs
  Assets/_Scripts/Actions/PubResetPointsAction.cs
  Assets/_Scripts/Actions/UpgradeWeaponAction.cs
  Assets/_Scripts/States/PlayerState.cs
  Assets/_Scripts/States/SceneState.cs
  Assets/_Scripts/Tests/ActionTest.cs
  Assets/_Scripts/Tests/PlayerStateTest.cs
Labels: Large

#52 Refactor/mutatable weapon
  Assets/_Scripts/Actions/BattleAction.cs
  Assets/_Scripts/Actions/CreateAccountAction.cs
  Assets/_Scripts/Actions/PubHealAction.cs
  Assets/_Scripts/Actions/ResetSessionAction.cs
  Assets/_Scripts/Actions/SellWeaponAction.cs
  Assets/_Scripts/Actions/UpgradeWeaponAction.cs
  Assets/_Scripts/States/PlayerState.cs
  Assets/_Scripts/States/WeaponState.cs
  Assets/_Scripts/Tests/ActionTest.cs
Labels: Extra Large

#53 Inventory removed
  Assets/_Scripts/States/PlayerState.cs
  Assets/_Scripts/Tests/ActionTest.cs
Labels: Extra Small

#55 Refactor/remove smith item stand
  Assets/_Scripts/Actions/InitializeStatesAction.cs
  Assets/_Scripts/Actions/InitializeStatesActionPlainValue.cs
  Assets/_Scripts/Actions/SellWeaponAction.cs
  Assets/_Scripts/Models/Encounters/Encounter.cs
  Assets/_Scripts/Models/Encounters/SmithEncounter.cs
  Assets/_Scripts/States/SceneState.cs
  Assets/_Scripts/Utils.cs
Labels: Small

#56 Meta file fix
  Assets/_Scripts/Actions/SellWeaponAction.cs.meta
Labels: Extra Small

#57 Sell action test removed
  Assets/_Scripts/Tests/ActionTest.cs
Labels: Extra Small

#61 Fixed zero cost upgrade
  Assets/_Scripts/States/WeaponState.cs
  Assets/_Scripts/Tests/ActionTest.cs
Labels: Extra Small

#62 Remove weapons preset
  Assets/_Scripts/Actions/InitializeStatesAction.cs
  Assets/_Scripts/Actions/InitializeStatesActionPlainValue.cs
  Assets/_Scripts/Game.cs
  Assets/_Scripts/States/EnvironmentState.cs
  Assets/_Scripts/Tests/ActionTest.cs
Labels: Extra Small

#63 Implment rendering feature for BattleAction
  Assets/Scenes/TestScene.unity
  Assets/_Scripts/Actions/BattleAction.cs
  Assets/_Scripts/EncounterHandler.cs
  Assets/_Scripts/Game.cs
  Assets/_Scripts/UI/BattleUI.cs
Labels: Small

#64 Implement single battle.
  Assets/Scenes/TestScene.unity
  Assets/_Scripts/Battle/BattleSimulator.cs
  Assets/_Scripts/Battle/Model/Character.cs
  Assets/_Scripts/EncounterHandler.cs
  Assets/_Scripts/Models/Encounters/BattleEncounter.cs
  Assets/_Scripts/Models/Encounters/Encounter.cs
  Assets/_Scripts/States/SceneState.cs
  Assets/_Scripts/UI/BattleSkillDecision.cs
  Assets/_Scripts/UI/BattleUI.cs
Labels: Medium

#59 Refactor/teardown
  Assets/Scenes/TestScene.unity
  Assets/_Scripts/Actions/BattleAction.cs
  Assets/_Scripts/Actions/CreateAccountAction.cs
  Assets/_Scripts/Actions/ExitPubAction.cs
  Assets/_Scripts/Actions/ExitSmithAction.cs
  Assets/_Scripts/Actions/InitializeStatesAction.cs
  Assets/_Scripts/Actions/InitializeStatesActionPlainValue.cs
  Assets/_Scripts/Actions/PubHealAction.cs
  Assets/_Scripts/Actions/PubResetPointsAction.cs
  Assets/_Scripts/Actions/ResetSessionAction.cs
  Assets/_Scripts/Actions/SellWeaponAction.cs
  Assets/_Scripts/Actions/SellWeaponAction.cs.meta
  Assets/_Scripts/Actions/UpgradeWeaponAction.cs
  Assets/_Scripts/EncounterHandler.cs
  Assets/_Scripts/Game.cs
  Assets/_Scripts/Models/BattleEvent.cs
  Assets/_Scripts/Models/BattleEvent.cs.meta
  Assets/_Scripts/Models/Encounters/BattleEncounter.cs
  Assets/_Scripts/Models/Encounters/Encounter.cs
  Assets/_Scripts/Models/Encounters/PubEncounter.cs
  Assets/_Scripts/Models/Encounters/SmithEncounter.cs
  Assets/_Scripts/Models/IEvent.cs
  Assets/_Scripts/Models/IEvent.cs.meta
  Assets/_Scripts/Models/Session.cs
  Assets/_Scripts/Models/Session.cs.meta
  Assets/_Scripts/Models/ShopEvent.cs
  Assets/_Scripts/Models/ShopEvent.cs.meta
  Assets/_Scripts/Models/Stage.cs
  Assets/_Scripts/Models/Stage.cs.meta
  Assets/_Scripts/Models/WorkshopEvent.cs
  Assets/_Scripts/Models/WorkshopEvent.cs.meta
  Assets/_Scripts/States/EnvironmentState.cs
  Assets/_Scripts/States/PlayerState.cs
  Assets/_Scripts/States/SceneState.cs
  Assets/_Scripts/States/WeaponState.cs
  Assets/_Scripts/Tests/ActionTest.cs
  Assets/_Scripts/Tests/ModelTest.cs
  Assets/_Scripts/Tests/ModelTest.cs.meta
  Assets/_Scripts/Tests/PlayerStateTest.cs
  Assets/_Scripts/UI/BattleSkillDecision.cs
  Assets/_Scripts/UI/BattleUI.cs
  Assets/_Scripts/Utils.cs
Labels: Extra Large

#65 bug fix in selecting skill
  Assets/_Scripts/EncounterHandler.cs
Labels: Extra Small

#66 Change encoding to UTF-8
  Assets/_Scripts/UI/StatView.cs
  Assets/_Scripts/UI/TurnView.cs
Labels: Extra Small

#67 Fix more encoding
  Assets/_Scripts/Util/LogExtension.cs
Labels: Extra Small
